### ISSUE TITLE
Hostname is getting lost and SNI fails

### ISSUE THREAD

**Issue by mpietruschka** [wildfly/wildfly-http-client#106]
I try to load balance more than one application/servers. To make that happen I use NGINX as Reverse proxy. It terminates incoming HTTPS-Connections and forwards the unencrypted data to the next jboss-server. Services are distinguished by the hostname/dns. So connections must support SNI.

After this approach didn't work I did some debugging and found out that TLS-Handshakes are done by the IP-Address. This is wrong since the Reverse Proxy needs to know the hostname before serving the right certificate/service. This makes NGINX run its fallback behavior serving its default website.

After some digging I found out that HttpConnectionPool.runPending() prepares a new URI for the underlaying UndertowClient-Connection. During that the hostname is getting lost.

Undertow seems handling SNI the right way => StreamConnectionChannelListener.handleEvent()

**HttpConnectionPool.runPending()**
(...)
       try {

            final SSLContext context = sslContext;
            UndertowClient.getInstance().connect(new ClientCallback<ClientConnection>() {
                @Override
                public void completed(ClientConnection result) {
                    result.getCloseSetter().set((ChannelListener<ClientConnection>) connections::remove);
                    ClientConnectionHolder clientConnectionHolder = new ClientConnectionHolder(result, hostPoolAddress.getURI(), context);
                    clientConnectionHolder.tryAcquire(); //aways suceeds
                    next.connectionListener.done(clientConnectionHolder);
                }

                @Override
                public void failed(IOException e) {
                    hostPoolAddress.failed(); //notify the host pool that this host has failed
                    activeInvocationCount.decrementAndGet();
                    next.errorListener.error(e);
                }
            }, new URI(hostPoolAddress.getURI().getScheme(), hostPoolAddress.getURI().getUserInfo(), address.getHostAddress(), hostPoolAddress.getURI().getPort(), "/", null, null), worker, ssl, byteBufferPool, options);
        } catch (URISyntaxException e) {
            next.errorListener.error(e);
        }
    }
(...)

This could be solved by passing the Hostname or the IP-Address (in case there’s no hostname). This function is provided by InetAddress.getHostName(). Using address.getHostAddress() in-place of address.getHostAddress() should do the job.

Could you please fix that issue?

Thanks!

**Comment by mpietruschka** [comment]
This seems to be fixed with [WEJBHTTP-74]

**Comment by fl4via** [comment]
Thank you @mpietruschka
